title: Press
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7040817
  brandStrength: 0.8372717
  lightness: 0.1552095
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  rhythmicContrast: 0.1852846
navigation:
  - name: BLOG
    url: 'http://www.ClaudioRaimondi.com'
    type: external
  - name: ABOUT ME
    url: 'http://claudioraimondi.com/claudio-raimondi/'
    type: external
  - name: PRESS
    url: 'http://press.ClaudioRaimondi.com'
    type: external
  - name: Twitter
    url: 'http://www.twitter.com/ClaudioRaimondi'
    type: external
  - name: LinkedIn
    url: 'http://linkedin.com/in/CRaimondi'
    type: external
analytics:
  twitter: null
  google: UA-5050578-6
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
name: 'Claudio Raimondi, General Manager at eBay in Italy'
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8776825177483261
layout_spectrum: 0.6978858392685652
