typography_spectrum: 0.05023573129437864
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.6942080627195537
  lightness: 0.4147197452839464
  saturation: 0.5678478369954973
  rhythmicContrast: 0.27968700509518385
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.04521138500422239
analytics:
  google: UA-5050578-6
  facebook: null
  twitter: null
name: Claudio Raimondi - Press
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Media & Press
purpose: []
