name: Claudio Raimondi - Press
favicon: null
layout_spectrum: 0.81276
typography_spectrum: 0.87906
title: 'Media & Press'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-5050578-6
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dd1c1a'
    - '#fff1d0'
    - '#086788'
    - '#06aed5'
    - '#f0c808'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
