typography_spectrum: 0.2608660876285285
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.4659188808873296
  lightness: 0.4627013292629272
  saturation: 0.4696422559209168
  rhythmicContrast: 0.6465198223013431
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.30295288865454495
analytics:
  google: UA-5050578-6
  facebook: null
  twitter: null
name: 'Claudio Raimondi, General Manager at eBay in Italy'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: BLOG
    url: 'http://www.ClaudioRaimondi.com'
    type: external
  - name: ABOUT ME
    url: 'http://claudioraimondi.com/claudio-raimondi/'
    type: external
  - name: PRESS & MEDIA
    url: 'http://press.ClaudioRaimondi.com'
    type: external
  - name: Twitter
    url: 'http://www.twitter.com/ClaudioRaimondi'
    type: external
  - name: LinkedIn
    url: 'http://linkedin.com/in/CRaimondi'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Media & Press
purpose: []
