name: Claudio Raimondi - Press
favicon: null
layout_spectrum: 0.81276
typography_spectrum: 0.87906
title: 'Media & Press'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-5050578-6
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffbf00'
    - '#e83f6f'
    - '#32936f'
    - '#3e2d54'
  brandStrength: 1
  lightness: 0.7373791
  saturation: 1
  rhythmicContrast: 1
purpose: []
