typography_spectrum: 0.6968080489896238
color:
  saturation: 0.060814984142780304
  brandStrength: 0.526217112550512
  lightness: 0.8409326430410147
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  rhythmicContrast: 0.5684835526626557
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.29255498363636434
analytics:
  twitter: null
  google: UA-5050578-6
  facebook: null
name: 'Claudio Raimondi, General Manager at eBay in Italy'
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: BLOG
    url: 'http://www.ClaudioRaimondi.com'
    type: external
  - name: ABOUT ME
    url: 'http://claudioraimondi.com/claudio-raimondi/'
    type: external
  - name: PRESS
    url: 'http://press.ClaudioRaimondi.com'
    type: external
  - name: Twitter
    url: 'http://www.twitter.com/ClaudioRaimondi'
    type: external
  - name: LinkedIn
    url: 'http://linkedin.com/in/CRaimondi'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Press
purpose: []
