typography_spectrum: 0.46465
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.5625
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74629
analytics:
  google: UA-5050578-6
  facebook: null
  twitter: null
name: 'Claudio Raimondi, General Manager at eBay in Italy'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: BLOG
    url: 'http://www.ClaudioRaimondi.com'
    type: external
  - name: ABOUT ME
    url: 'http://claudioraimondi.com/claudio-raimondi/'
    type: external
  - name: on Twitter
    url: 'http://www.twitter.com/ClaudioRaimondi'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Claudio Raimondi - Press
description: Press
purpose: []
